export const doctorsData = [
  { id: 1, name: 'Dr. Patel', expertise: 'Physiotherapy', city: 'Mumbai', sessionDuration: 50 },
  { id: 2, name: 'Dr. Sharma', expertise: 'Sports Medicine', city: 'Delhi', sessionDuration: 50 },
  { id: 3, name: 'Dr. Kumar', expertise: 'Sports Medicine', city: 'Bangalore', sessionDuration: 50 },
  { id: 4, name: 'Dr. Gupta', expertise: 'Rehabilitation', city: 'Chennai', sessionDuration: 50 },
  { id: 5, name: 'Dr. Singh', expertise: 'Orthopedic', city: 'Hyderabad', sessionDuration: 50 },
  { id: 6, name: 'Dr. Verma', expertise: 'Cardiology', city: 'Pune', sessionDuration: 50 },
  { id: 7, name: 'Dr. Reddy', expertise: 'Neurology', city: 'Kolkata', sessionDuration: 50 },
  { id: 8, name: 'Dr. Agarwal', expertise: 'Dermatology', city: 'Ahmedabad', sessionDuration: 50 },
  { id: 9, name: 'Dr. Joshi', expertise: 'Psychiatry', city: 'Jaipur', sessionDuration: 50 },
  { id: 10, name: 'Dr. Yadav', expertise: 'Gastroenterology', city: 'Lucknow', sessionDuration: 50 },
  { id: 11, name: 'Dr. Malhotra', expertise: 'Ophthalmology', city: 'Chandigarh', sessionDuration: 50 },
  { id: 12, name: 'Dr. Khanna', expertise: 'Pediatrics', city: 'Nagpur', sessionDuration: 50 },
  { id: 13, name: 'Dr. Kapoor', expertise: 'Obstetrics and Gynecology', city: 'Indore', sessionDuration: 50 },
  { id: 14, name: 'Dr. Bansal', expertise: 'ENT', city: 'Agra', sessionDuration: 50 },
  { id: 15, name: 'Dr. Verma', expertise: 'Internal Medicine', city: 'Varanasi', sessionDuration: 50 },
  { id: 16, name: 'Dr. Singhania', expertise: 'Urology', city: 'Bhopal', sessionDuration: 50 },
  { id: 17, name: 'Dr. Choudhary', expertise: 'Dentistry', city: 'Patna', sessionDuration: 50 },
  { id: 18, name: 'Dr. Sharma', expertise: 'Psychology', city: 'Ranchi', sessionDuration: 50 },
  { id: 19, name: 'Dr. Yadav', expertise: 'Rheumatology', city: 'Kochi', sessionDuration: 50 },
  { id: 20, name: 'Dr. Kapoor', expertise: 'Plastic Surgery', city: 'Thiruvananthapuram', sessionDuration: 50 },
];
